languageCode = "en-us"
baseURL = "https://www.example.org/"
theme = "aafu"

[params]
author = "Mountain Head"
copyright = "mountain head"
description = "Welcome to the TOP"
title = "Mountain Head"

[params.aboutme]
description = "**Tagline. Lorem ipsum dolor sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
icon = "fas fa-user"
title = "About Me"

[params.education]
icon = "fas fa-graduation-cap"
title = "Education"

[[params.education.list]]
college = "University of State-City"
dates = "2013 - 2018"
degree = "Ph.D. in Subject"
thesis_link = "#"
thesis_title = "Effect of humans on other humans: a study of human behavior."

[[params.education.list]]
college = "University of State-City"
dates = "2013 - 2018"
degree = "M.S. in Subject"
thesis_link = "#"
thesis_title = "Effect of humans on other humans: a study of human behavior."

[[params.education.list]]
college = "University of State-City"
dates = "2004 - 2009"
degree = "B.S. in Subject"

[params.experience]
icon = "fas fa-briefcase"
title = "Experiences"

[[params.experience.list]]
company = "Mountain Head"
dates = "2019 - *Present*"
details = "Printed from desktop. Sent [emails](#). Called people using telephone. Drank water from office cooler. Ate donuts on people's birthdays."
position = "Uphill Manager"

[[params.experience.list]]
company = "Company Name"
dates = "2018 - 2019"
link = "#"
position = "Job Title"

[params.favicons]
metas = "        <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"apple-touch-icon.png\">\r\n        <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"favicon-32x32.png\">\r\n        <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"favicon-16x16.png\">\r\n        <link rel=\"manifest\" href=\"site.webmanifest\">\r\n        <link rel=\"mask-icon\" href=\"safari-pinned-tab.svg\" color=\"#252627\">\r\n        <link rel=\"shortcut icon\" href=\"favicon.ico\">\r\n        "
use = true

[params.hobby]
icon = "fas fa-gamepad"
title = "Hobbies"

[[params.hobby.list]]
hobby = "Cooking"

[[params.hobby.list]]
hobby = "Hiking"

[[params.hobby.list]]
hobby = "Baking"

[params.profile]
location = "Delhi, India"
name = "Mountain Head"
photo = "profile-1.jpg"
tagline = "Title"

[params.project]
icon = "fas fa-project-diagram"
title = "Projects"

[[params.project.list]]
description = "Description of the project"
title = "project"
url = "#"

[[params.project.list]]
description = "Description of the project"
title = "project"
url = "#"

[[params.project.list]]
description = "Description of the project"
title = "project"
url = "#"

[[params.project.list]]
description = "Description of the project"
title = "project"
url = "#"

[params.publication]
format = ["date", "authors", "title", "journal"]
icon = "fas fa-book"
title = "Publications"
types = ["Journal Articles", "Proceedings"]

[[params.publication.list]]
authors = "F Last, F Second, P secondary"
date = "2018"
journal = "Journal of Field 52 (16), 9033-9044"
link = "#"
title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
type = "Journal Articles"

[[params.publication.list]]
authors = "F Last, F Second, P secondary"
date = "2018"
journal = "Journal of Field 52 (16), 9033-9044"
link = "#"
title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
type = "Journal Articles"

[[params.publication.list]]
authors = "F Last, F Second, P secondary"
date = "2018"
journal = "Journal of Field 52 (16), 9033-9044"
link = "#"
title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
type = "Proceedings"

[[params.showInAccordion]]
expand = true
item = "aboutme"

[[params.showInAccordion]]
item = "experience"

[[params.showInAccordion]]
item = "education"

[[params.showInAccordion]]
item = "publication"

[[params.showInAccordion]]
item = "project"

[[params.showInAccordion]]
item = "skill"

[[params.showInAccordion]]
item = "hobby"

[params.skill]
icon = "fas fa-cogs"
panelId = "skill-panel"
title = "Skills"

[[params.skill.list]]
skill = "Skill 1, Skill 2"
skillrating = 90

[[params.skill.list]]
skill = "Skill 3"
skillrating = 80

[[params.skill.list]]
skill = "Skill 4"
skillrating = 50

[params.social]
title = "Links"

[[params.social.list]]
class = "fab"
icon = "fa-linkedin-in"
title = "LinkedIn"
url = "#"

[[params.social.list]]
class = "fab"
icon = "fa-stack-overflow"
title = "StackOverflow"
url = "#"

[[params.social.list]]
class = "fab"
icon = "fa-github"
title = "GitHub"
url = "#"

[[params.social.list]]
class = "fab"
icon = "fa-twitter"
title = "Twitter"
url = "#"

[[params.social.list]]
class = "ai"
icon = "ai-google-scholar"
title = "Google Scholar"
url = "#"

[[params.social.list]]
class = "ai"
icon = "ai-researchgate"
title = "ResearchGate"
url = "#"

[params.theme]
allowToggle = true
altTheme = "dark"
mainTheme = "light"
showAttribute = true